controllers/AuthController.php
<?php

namespace app\controllers;

use app\models\SignUpForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class AuthController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignUp()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new SignUpForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signUp()) {
                if (Yii::$app->getUser()->login($user)) {
                    $authManager = \Yii::$app->authManager;
                    $userRole = $authManager->getRole("user");
                    $authManager->assign($userRole, Yii::$app->user->id);
                    return $this->goHome();
                }
            }
        }

        return $this->render('sign-up', [
            'model' => $model,
        ]);
    }
}

views/layouts/company.php
<?php

use yii\bootstrap\Nav;

/**
 * @var $content string
 * @var $company \app\models\Company
 */

?>



<h1>Company <?= $company->name ?></h1>

<br>

<?php

echo Nav::widget([
    'items' => [
        [
            'label' => 'Overview',
            'url' => ['company/view', 'id' => $company->id],
        ],
        [
            'label' => 'Masters',
            'url' => ['master/index', 'id' => $company->id],
        ],
        [
            'label' => 'Articles',
            'url' => ['article/index', 'id' => $company->id],
        ],
        [
            'label' => 'Item Groups',
            'url' => ['group/index', 'id' => $company->id],
        ],
        [
            'label' => 'Privileges',
            'url' => ['privileges/index', 'id' => $company->id],
        ],

    ],
    'options' => [
        'class' =>'nav-pills',
        'style' => 'background-color: #f5f5f5;'
    ],
]);
?>

<br>

<?= $content ?>

views/layouts/main.php
<?php

/**
 * @var $this \yii\web\View
 * @var $content string
 */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Company App',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'All Companies', 'url' => ['/']],
            ['label' => 'Sign Up', 'url' => ['/auth/sign-up'],
                'visible' => Yii::$app->user->isGuest],
            Yii::$app->user->isGuest ?
                ['label' => 'Login', 'url' => ['/auth/login']] :
                [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/auth/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>